[package]
name = "bonding-curve-contract-meta"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[dependencies.bonding-curve-contract]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.3"
path = "../../../../framework/meta-lib"
default-features = false
