[package]
name = "rust-interact"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "rust-interact"
path = "src/interactor_main.rs"

[dependencies.rust-snippets-generator-test]
path = ".."

[dependencies.drt-sc-snippets]
version = "0.0.2"
path = "../../../../framework/snippets"

# [workspace]


