[package]
name = "erc1155-marketplace-meta"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[dependencies.erc1155-marketplace]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.1"
path = "../../../../../framework/meta-lib"
default-features = false
