[package]
name = "abi-tester-meta"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[dependencies.abi-tester]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.1"
path = "../../../../framework/meta-lib"
default-features = false
