// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    scenario_tester
    (
        init => init
        upgrade => upgrade
        getSum => sum
        add => add
        multi_param => multi_param
        multi_return => multi_return
    )
}

drt_sc_wasm_adapter::async_callback_empty! {}
