// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    digital_cash
    (
        init => init
        whitelistFeeToken => whitelist_fee_token
        blacklistFeeToken => blacklist_fee_token
        claimFees => claim_fees
        getAmount => get_amount
        payFeeAndFundDCT => pay_fee_and_fund_dct
        payFeeAndFundREWA => pay_fee_and_fund_rewa
        fund => fund
        depositFees => deposit_fees
        withdraw => withdraw
        claim => claim
        forward => forward
        deposit => deposit
    )
}

drt_sc_wasm_adapter::async_callback_empty! {}
