[package]
name = "ping-pong-rewa"
version = "0.0.2"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.2"
path = "../../../framework/scenario"

