[package]
name = "nft-subscription-meta"
version = "0.0.0"
authors = ["Thouny <thouny@tuta.io>"]
edition = "2021"
publish = false

[dependencies.nft-subscription]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.1"
path = "../../../../framework/meta-lib"
default-features = false
