[package]
name = "basic-interact"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "basic-interact"
path = "src/basic_interact.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.6"

[dependencies.adder]
path = ".."

[dependencies.drt-sc-snippets]
version = "0.0.2"
path = "../../../../framework/snippets"
