[package]
name = "vec-repeat"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/vec_repeat.rs"

[dependencies.benchmark-common]
path = "../benchmark-common"


[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"
