[package]
name = "erc1155"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/erc1155.rs"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"

[dev-dependencies.erc1155-user-mock]
path="../erc1155-user-mock"
