[package]
name = "forwarder-queue"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/forwarder_queue.rs"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"

[dependencies.drt-sc-wasm-adapter]
version = "0.0.1"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"
