[package]
name = "forwarder-legacy"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/forwarder_legacy_main.rs"

[dependencies.vault]
path = "../vault"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.2"
path = "../../../../framework/scenario"

