[package]
name = "ping-pong-rewa-meta"
version = "0.0.0"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2021"
publish = false

[dependencies.ping-pong-rewa]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.1"
path = "../../../../framework/meta-lib"
default-features = false
