[package]
name = "lottery-erc20"
version = "0.0.0"
authors = [ "xfactor <xfactor.toml@gmail.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"
