[package]
name = "check-pause-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]

[dependencies.check-pause]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.3"
path = "../../../../framework/meta-lib"
default-features = false
