// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    check_pause
    (
        init => init
        checkPause => check_pause
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

drt_sc_wasm_adapter::async_callback_empty! {}
