[package]
name = "erc1155-marketplace"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.erc1155]
path = "../erc1155"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"
