[package]
name = "dcdt-transfer-with-fee-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dcdt-transfer-with-fee]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.2"
path = "../../../../framework/meta-lib"
default-features = false
