[package]
name = "proxy-test-second"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/proxy-test-second.rs"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.drt-sc-scenario]
version = "0.0.2"
path = "../../../../framework/scenario"
