[package]
name = "proxy-test-second-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.proxy-test-second]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.3"
path = "../../../../../framework/meta-lib"
default-features = false
