// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    nft_subscription
    (
        init => init
        issue => issue
        mint => mint
        update_attributes => update_attributes
        renew => renew
        cancel => cancel
    )
}

drt_sc_wasm_adapter::async_callback! { nft_subscription }
