[package]
name = "builtin-func-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.builtin-func-features]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.2"
path = "../../../../../framework/meta-lib"
default-features = false
