[package]
name = "execute-on-dest-dcdt-issue-callback"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.parent]
path = "parent"

[dependencies.child]
path = "child"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.2"
path = "../../../framework/scenario"
