[package]
name = "kitty"
version = "0.0.0"
authors = [ "xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../../../framework/base"

[dependencies.random]
version = "0.0.0"
path = "../random"
