[package]
name = "crowdfunding-erc20"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/crowdfunding_erc20.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.drt-sc]
version = "0.0.2"
path = "../../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.2"
path = "../../../../framework/scenario"

