[package]
name = "nft-subscription"
version = "0.0.0"
authors = ["Thouny <thouny@tuta.io>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../framework/base"

[dependencies.drt-sc-modules]
version = "0.0.1"
path = "../../../contracts/modules"

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../framework/scenario"
