[package]
name = "proxy-pause-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]

[dev-dependencies]

[dependencies.proxy-pause]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.2"
path = "../../../../framework/meta-lib"
default-features = false
