// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    crypto_bubbles
    (
        init => init
        topUp => top_up
        withdraw => withdraw
        joinGame => join_game
        rewardWinner => reward_winner
        rewardAndSendToWallet => reward_and_send_to_wallet
        balanceOf => player_balance
    )
}

drt_sc_wasm_adapter::async_callback_empty! {}
