// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            0
// Async Callback:                       1
// Total number of exported functions:   3

#![no_std]

drt_sc_wasm_adapter::allocator!();
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    forwarder_raw
    (
        init => init_async_call
        upgrade => upgrade_async_call
    )
}

drt_sc_wasm_adapter::async_callback! { forwarder_raw }
