[package]
name = "format-tests"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "format-tests"
path = "src/format_tests.rs"

[dependencies.drt-sc]
version = "=0.0.3"
path = "../../../framework/base"

[dependencies.drt-sc-scenario]
version = "=0.0.3"
path = "../../../framework/scenario"

[dependencies.drt-chain-vm]
version = "=0.0.3"
path = "../../../vm"

[dev-dependencies]
glob = "0.3.0"
home = "0.5.2"

[workspace]
members = ["."]
