[package]
name = "token-release"
version = "0.0.1"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/token_release.rs"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../framework/base"

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../framework/scenario"

