[package]
name = "seed-nft-minter-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["xfactor <xfactor.toml@gmail.com>"]

[dev-dependencies]

[dependencies.seed-nft-minter]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.1"
path = "../../../../framework/meta-lib"
default-features = false
