// Code generated by the drt-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

drt_sc_wasm_adapter::allocator!(static64k);
drt_sc_wasm_adapter::panic_handler!();

drt_sc_wasm_adapter::endpoints! {
    proxy_test_second
    (
        init => init
        upgrade => upgrade
        payMe => pay_me
        payMeWithResult => pay_me_with_result_endpoint
        messageMe => message_me
    )
}

drt_sc_wasm_adapter::async_callback_empty! {}
