[package]
name = "erc721-meta"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[dependencies.erc721]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.3"
path = "../../../../../framework/meta-lib"
default-features = false
