[package]
name = "proxy-test-first"
version = "0.0.0"
authors = ["xfactor <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/proxy-test-first.rs"

[dependencies]
hex-literal = "0.4.1"

[dependencies.drt-sc]
version = "0.0.1"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.drt-sc-scenario]
version = "0.0.1"
path = "../../../../framework/scenario"
