[package]
name = "dcdt-system-sc-mock-meta"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[dependencies.dcdt-system-sc-mock]
path = ".."

[dependencies.drt-sc-meta-lib]
version = "0.0.2"
path = "../../../../framework/meta-lib"
default-features = false
