[package]
name = "promises-features"
version = "0.0.0"
authors = ["xfactor-toml <xfactor.toml@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/promises_main.rs"

[dependencies.drt-sc]
version = "0.0.3"
path = "../../../../framework/base"

